### ISSUE TITLE
Ability to start processInstance with BusinessKey

### ISSUE THREAD

**Issue by ronalders** [camunda/camunda-bpm-assert-scenario#10]
Is there a possibility to start the de process Instance with a businessKey. I only see a way to start test a instance with variables. 

Or this already possible ?

**Comment by martinschimak** [comment]
Hello,

Many thanks for your question! It is already possible, because the "primary" mechanism to start a new process instance is to write your own process instantiation code by using the `startBy` method:

```java
Scenario.run(processScenario).startBy(() -> {
  return rule.getRuntimeService().startProcessInstanceByKey("myProcessKey", "myBusinessKey");
}).execute();
```

The other methods like "startByKey" and startByMessage" are just convenience methods to make the 80% - or eventually 95% - of use cases even faster to write. Having said that, we could of course allow for directly adding a business key to a scenario instance... I will therefore transform this into an improvement issue. Eventually you want to provide a pull request? 😄 

Many greetings, 
Martin.

**Comment by meyerdan** [comment]
Hi Matin,

just FYI, in recent versions, two methods with the following signature are available:

```java
ProcessInstantiationBuilder createProcessInstanceById(String processDefinitionId);
ProcessInstantiationBuilder createProcessInstanceByKey(String processDefinitionKey);
```

the returned builder then allows to set all optional parameters like variables and business key, tenant id etc. May also be an option to primarily expose that...

Best,
Daniel

**Comment by martinschimak** [comment]
Hi Daniel, many thx I am aware! - not unthinkable, I would  probably need to extend the builder interface in order to integrate it into the fluent scenario run builder ... but I am cautious with these things, because "scenario" is currently fully backwards compatible with all existing versions of Camunda BPM which is of value in itself for a community extension. 

(The above mentioned approach to create your own process instantiation function of course also allows to use those newer fluent builders Daniel speaks of!)

**Comment by Guchman** [comment]
https://github.com/camunda/camunda-bpm-assert-scenario/pull/39

**Comment by Guchman** [comment]
> just FYI, in recent versions, two methods with the following signature are available:
> 
> ```java
> ProcessInstantiationBuilder createProcessInstanceById(String processDefinitionId);
> ProcessInstantiationBuilder createProcessInstanceByKey(String processDefinitionKey);
> ```
Maybe it's an option, but I've not found any examples in ReadMe :(
