### ISSUE TITLE
Is there an ability to mock not a wait-state?

### ISSUE THREAD

**Issue by r-n-aliev** [camunda/camunda-bpm-assert-scenario#33]
I've found the phrase in project's README 
`Eliminate almost all querying for runtime objects as e.g. tasks, you get the instances injected into your actions`

But haven't found how to do this (e.g. [here](https://github.com/camunda/camunda-bpm-assert-scenario/blob/master/example/src/test/java/org/camunda/bpm/scenario/examples/insuranceapplication/InsuranceApplicationProcessTest.java)) - is this function present now?
How can i inject the stub of Service Task? Otherwise, if this Service Task does any request, **it's necessary to mock the appropriate service** even if you dont need to do this.

**Comment by martinschimak** [comment]
Hi @r-n-aliev - the library doesn't do anything with regards to "classical" service tasks (meaning: actively invoking some piece of code by means of job executor threads). You can however leverage the library to work with "external" service tasks (because they are waitstates). For "classical" service tasks, you can make use of normal mocking, as e.g. descibred here: https://camunda.com/best-practices/testing-process-definitions/#_mock_the_business_service_methods
