### ISSUE TITLE
How to test asyncBefore/asyncAfter ?

### ISSUE THREAD

**Issue by vprudnikov** [camunda/camunda-bpm-assert-scenario#37]
Hello,

I have a question related to async continuations.
It's critical for my process to set asyncBefore/asyncAfter for some tasks. It will be considered a bug if I forget to do this.

As I understand, camunda-bpm-assert-scenario automatically executes async continuations.
**Is it possible to check with camunda-bpm-assert-scenario that a task is async (i.e. I didn't forget to set asyncBefore/asyncAfter attributes for the task)?**

**Comment by martinschimak** [comment]
Hi,

with assert scenario you can intercept all natural wait states (such as
user tasks, external tasks, intermediate timer events etc etc) in such a
way that you can perform any assertion (or basically any code) at these
points, such as eg checking whether the current activity has an async
continuation flag. I cannot tell you out of my head how to do this exactly,
but you can certainly check these things by means of the camunda model
api). Having said this ... assert scenario is not directly meant to
validate such flow node characteristics for nodes which are not natural
wait states (such as eg traditional service tasks executed by the job
executor) but you can of course mock/intercept such points with more
traditional means (such as eg Mocks.register custom test beans) and then
you can more easily perform such checks, too.

Last not least ... the validation you are speaking about is actually not
one you need to create and run a process instance for. Because it’s a more
static check on the model you could also consider to validate your bpmn
model before you actually validate its runtime behavior.

All the best
Martin

vprudnikov <notifications@github.com> schrieb am Sa. 5. Sep. 2020 um 23:02:

**Comment by vprudnikov** [comment]
@martinschimak thanks for reply!

I have an async service task. I tried listening to `Scenario.waitsAtServiceTask(myTaskId)` but my callback was not executed (and this is expected I assume.)

If there is no way to check if a service task is async or not by using the assert scenario, could you please suggest any concrete solution that helps to check that developers have not fotgot to set 'asyncBefore/asyncAfter' attributes?

Thank you!

**Comment by martinschimak** [comment]
Hi,

please use the public camunda forums to discover the concrete solution,
because it's not an assert-scenario related problem.

Many thanks for your interest!
Martin

**Comment by vprudnikov** [comment]
for anyone who is interested in this topic, I figured out the following solution (code written in Groovy for Spock tests):

```
then:
1 * scenario.hasCompleted("myServiceTaskId") >> { String id -> assertThatServiceTaskIsAsync(id, processKey) }

...

static def assertThatServiceTaskIsAsync(String taskId, String processDefinitionKey) {
        assertThatServiceTaskIsAsync(taskId, processDefinition(processDefinitionKey))
}

static def assertThatServiceTaskIsAsync(String taskId, ProcessDefinition processDefinition) {
        def task = repositoryService()
                .getBpmnModelInstance(processDefinition.getId())
                .getModelElementById(taskId) as ServiceTask
        assert task.isCamundaAsyncBefore()
        assert task.isCamundaAsyncAfter()
}
```

**Comment by martinschimak** [comment]
Related to #38
