### ISSUE TITLE
Turn off ignoring transaction borders

### ISSUE THREAD

**Issue by r-n-aliev** [camunda/camunda-bpm-assert-scenario#38]
Framework by default ignores transaction borders. 
How to turn OFF this behaviour to stop at defined element with transaction? 
(to have done something and then go further with turned ON ignoring)

Thank you, Martin.

**Comment by martinschimak** [comment]
Hi, this is currently not possible and after having tried to enable such a thing initially, which forced me to think about it, I actually consider it a feature that it's not possible - until proven wrong :-) 

"Scenario" by design only stops at "natural wait states". The reason is, that adding or removing an optional transaction boundary should not change the business behavior of a process execution. Put differently: adding or removing a transaction boundary should not break tests which are written to validate business behavior only. "Scenario" was actually written, BECAUSE there are many ways in which traditional process tests break when you introduce changes which actually do not change the business behavior under test. And this is bad for any kind of test. 

(Furthermore, such a possibility would also lead to quite a few tough practical questions, because when you look into Camunda's detailed execution semantics it would not always be transparent for the test coder in which exact state the process actually stops when reaching such intermediate transaction borders and how often such a stop would be caused. When realizing this and after having thought about it, I came to the conclusion that this is just another consequence of transaction borders being a purely technical feature, not a feature allowing you to introduce/change business behavior. Therefore I think, even though it's probably not "impossible" to implement such a feature, it is complicated to do it properly and in a way which is helpful for the test coder. To the contrary, it could easily lead to many more ways to use the framework wrongly than it would contribute to get its usage right)

Are there ways to reach your goals differently? Very probably yes.

E.g. if you want to validate the existence of technical transaction boundaries, you can do that by validating your model with the Camunda Model API. Or if you want to validate that a service task (other than External Task) is called in a certain way, you can e.g. mock the service bean by traditional means, like e.g. with Mockito.
